// ============================================================
// AeroSense — Reports Screen  (Feature 12)
// Generates a shareable AQI report containing:
//   • Current AQI, pollutants, status
//   • ML 1-hour prediction
//   • Health recommendations
//   • Historical summary (last 7 days)
//   • Location + timestamp
// Share via OS share sheet (share_plus).
// ============================================================

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../providers/aqi_provider.dart';
import '../providers/location_provider.dart';
import '../theme/app_theme.dart';
import '../services/mock_ai_service.dart';
import '../widgets/screen_background.dart';

class ReportsScreen extends StatefulWidget {
  const ReportsScreen({super.key});
  @override
  State<ReportsScreen> createState() => _ReportsScreenState();
}

class _ReportsScreenState extends State<ReportsScreen> {
  bool _generating = false;

  String _buildReportText(AqiProvider aqi, LocationProvider loc) {
    final now = DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now());
    final pd  = aqi.livePollutants;
    final ml  = aqi.mlPrediction;

    final sb = StringBuffer();
    sb.writeln('═══════════════════════════════════════');
    sb.writeln('       AeroSense — AQI Report');
    sb.writeln('═══════════════════════════════════════');
    sb.writeln('📍 Location  : ${loc.locationLabel}');
    sb.writeln('🕐 Generated : $now');
    sb.writeln();

    // ── Current AQI ──────────────────────────────────
    sb.writeln('── CURRENT AIR QUALITY ─────────────────');
    sb.writeln('AQI Score : ${aqi.latestAqi.toStringAsFixed(1)}');
    sb.writeln('Status    : ${aqi.latestStatus}');
    sb.writeln('Temperature : ${aqi.latestTemperature.toStringAsFixed(1)} °C');
    sb.writeln('Humidity    : ${aqi.latestHumidity.toStringAsFixed(0)} %');
    sb.writeln('CO₂ (est.)  : ${aqi.latestCo2.toStringAsFixed(0)} ppm');
    sb.writeln('VOC (est.)  : ${aqi.latestVoc.toStringAsFixed(0)} ppb');
    sb.writeln();

    // ── Pollutants ────────────────────────────────────
    sb.writeln('── REAL-TIME POLLUTANTS (Open-Meteo) ───');
    if (pd != null) {
      void writeLine(String name, double? v, String unit) {
        sb.writeln('$name : ${v != null ? "${v.toStringAsFixed(1)} $unit" : "Data unavailable"}');
      }
      writeLine('PM2.5 ', pd.pm25.value, 'µg/m³');
      writeLine('PM10  ', pd.pm10.value, 'µg/m³');
      writeLine('NO₂   ', pd.no2.value,  'µg/m³');
      writeLine('SO₂   ', pd.so2.value,  'µg/m³');
      writeLine('O₃    ', pd.o3.value,   'µg/m³');
      writeLine('CO    ', pd.co.value,   'µg/m³');
    } else {
      sb.writeln('Pollutant data not yet fetched.');
    }
    sb.writeln();

    // ── ML Prediction ─────────────────────────────────
    sb.writeln('── ML PREDICTION (1-Hour Ahead) ────────');
    if (ml != null) {
      sb.writeln('Predicted AQI : ${ml.predictedAqi.toStringAsFixed(1)}');
      sb.writeln('Trend         : ${ml.trend}  (${ml.change})');
      sb.writeln('Confidence    : ${ml.confidencePct}');
      sb.writeln('Model MAE     : ±${ml.mae.toStringAsFixed(1)} AQI');
      sb.writeln('Source        : ${ml.isOnline ? "Python ML API (Random Forest)" : "Rule-based fallback"}');
    } else {
      sb.writeln('ML prediction not yet available.');
    }
    sb.writeln();

    // ── 7-day history ─────────────────────────────────
    final records = aqi.records;
    final cutoff  = DateTime.now().subtract(const Duration(days: 7));
    final week    = records.where((r) => r.timestamp.isAfter(cutoff)).toList();
    sb.writeln('── 7-DAY HISTORY SUMMARY ───────────────');
    if (week.isEmpty) {
      sb.writeln('No historical readings available.');
    } else {
      final aqis = week.map((r) => r.aqiScore).toList();
      final avg  = aqis.reduce((a, b) => a + b) / aqis.length;
      final best = aqis.reduce((a, b) => a < b ? a : b);
      final worst= aqis.reduce((a, b) => a > b ? a : b);
      final safe = aqis.where((a) => a <= 50).length;
      sb.writeln('Readings   : ${week.length}');
      sb.writeln('Average AQI: ${avg.toStringAsFixed(1)}');
      sb.writeln('Best AQI   : ${best.toStringAsFixed(1)}');
      sb.writeln('Worst AQI  : ${worst.toStringAsFixed(1)}');
      sb.writeln('Safe Days  : $safe');
    }
    sb.writeln();

    // ── Recommendations ───────────────────────────────
    sb.writeln('── HEALTH RECOMMENDATIONS ──────────────');
    final recs = _healthRecs(aqi.latestStatus);
    for (final r in recs) { sb.writeln('• $r'); }
    sb.writeln();

    sb.writeln('═══════════════════════════════════════');
    sb.writeln('Generated by AeroSense — Air Quality Checker');
    sb.writeln('Data sources: Open-Meteo (free, no API key)');
    sb.writeln('═══════════════════════════════════════');
    return sb.toString();
  }

  List<String> _healthRecs(String status) {
    switch (status) {
      case 'Safe'     : return [
        'Air quality is good — safe for all outdoor activities.',
        'Great day for exercise, cycling, or a walk.',
      ];
      case 'Moderate' : return [
        'Generally safe; sensitive individuals should limit strenuous outdoor exertion.',
        'Stay hydrated.',
      ];
      case 'Warning'  : return [
        'People with asthma or respiratory conditions should stay indoors.',
        'Wear N95 mask if outdoor exposure is necessary.',
        'Keep windows closed and run an air purifier if available.',
      ];
      default         : return [
        'HAZARDOUS: Stay indoors. Avoid all outdoor activities.',
        'Use N95/FFP2 mask and eye protection if outdoor exposure is unavoidable.',
        'Run air purifier on highest setting. Consult a doctor if symptoms arise.',
      ];
    }
  }

  Future<void> _shareReport() async {
    if (!mounted) return;
    final aqi = context.read<AqiProvider>();
    final loc = context.read<LocationProvider>();
    setState(() => _generating = true);
    await Future<void>.delayed(const Duration(milliseconds: 300));
    final text = _buildReportText(aqi, loc);
    if (!mounted) return;
    setState(() => _generating = false);
    await Share.share(text, subject: 'AeroSense AQI Report — ${loc.locationLabel}');
  }

  @override
  Widget build(BuildContext context) {
    return Consumer2<AqiProvider, LocationProvider>(
      builder: (context, aqi, loc, _) {
        final pd      = aqi.livePollutants;
        final ml      = aqi.mlPrediction;
        final records = aqi.records;
        final cutoff  = DateTime.now().subtract(const Duration(days: 7));
        final week    = records.where((r) => r.timestamp.isAfter(cutoff)).toList();
        final aqis    = week.map((r) => r.aqiScore).toList();
        final avg     = aqis.isNotEmpty
            ? aqis.reduce((a, b) => a + b) / aqis.length
            : 0.0;
        final statusColor = MockAiService.getStatusColor(aqi.latestStatus);

        return Scaffold(
          backgroundColor: AppTheme.scaffoldBg,
          body: ScreenBackground(
            theme: ScreenTheme.history,
            child: SafeArea(
              child: CustomScrollView(
                slivers: [
                  SliverToBoxAdapter(
                    child: Padding(
                      padding: const EdgeInsets.all(20),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // ── Header ─────────────────────────────
                          Row(children: [
                            Container(
                              width: 40, height: 40,
                              decoration: BoxDecoration(
                                gradient: const LinearGradient(
                                  colors: [Color(0xFF3B6FE8), Color(0xFF48CAE4)],
                                ),
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: const Icon(Icons.summarize_rounded,
                                  color: Colors.white, size: 22),
                            ),
                            const SizedBox(width: 12),
                            const Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text('AQI Report',
                                    style: TextStyle(fontSize: 20,
                                        fontWeight: FontWeight.w800,
                                        color: AppTheme.textPrimary)),
                                Text('Current snapshot of your air quality',
                                    style: TextStyle(fontSize: 11,
                                        color: AppTheme.textSecondary)),
                              ],
                            ),
                          ]),
                          const SizedBox(height: 6),
                          Text(
                            '📍 ${loc.locationLabel}  •  '
                            '${DateFormat("dd MMM yyyy, hh:mm a").format(DateTime.now())}',
                            style: const TextStyle(
                                fontSize: 11, color: AppTheme.textSecondary),
                          ),
                          const SizedBox(height: 20),

                          // ── AQI Summary card ───────────────────
                          _ReportSection(
                            title: 'Current Air Quality',
                            icon : Icons.air_rounded,
                            iconColor: statusColor,
                            child: Column(children: [
                              Row(children: [
                                Container(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 18, vertical: 12),
                                  decoration: BoxDecoration(
                                    color: statusColor.withOpacity(0.10),
                                    borderRadius: BorderRadius.circular(14),
                                    border: Border.all(
                                        color: statusColor.withOpacity(0.30)),
                                  ),
                                  child: Column(children: [
                                    Text(aqi.latestAqi.toStringAsFixed(1),
                                        style: TextStyle(fontSize: 32,
                                            fontWeight: FontWeight.w900,
                                            color: statusColor)),
                                    const Text('AQI',
                                        style: TextStyle(fontSize: 11,
                                            color: AppTheme.textSecondary)),
                                  ]),
                                ),
                                const SizedBox(width: 14),
                                Expanded(child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 10, vertical: 4),
                                      decoration: BoxDecoration(
                                        color: statusColor,
                                        borderRadius: BorderRadius.circular(10),
                                      ),
                                      child: Text(aqi.latestStatus,
                                          style: const TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.w800,
                                              fontSize: 13)),
                                    ),
                                    const SizedBox(height: 8),
                                    _ReportRow('Temperature',
                                        '${aqi.latestTemperature.toStringAsFixed(1)} °C'),
                                    _ReportRow('Humidity',
                                        '${aqi.latestHumidity.toStringAsFixed(0)} %'),
                                    _ReportRow('CO₂ (est.)',
                                        '${aqi.latestCo2.toStringAsFixed(0)} ppm'),
                                  ],
                                )),
                              ]),
                            ]),
                          ),
                          const SizedBox(height: 14),

                          // ── Pollutants ─────────────────────────
                          _ReportSection(
                            title: 'Real-Time Pollutants',
                            icon : Icons.grain_rounded,
                            iconColor: const Color(0xFF43A047),
                            child: pd == null
                                ? const Text('Fetching pollutant data…',
                                    style: TextStyle(fontSize: 12,
                                        color: AppTheme.textSecondary))
                                : Wrap(spacing: 8, runSpacing: 8, children: [
                                    _PollChip('PM2.5', pd.pm25.value, 'µg/m³'),
                                    _PollChip('PM10',  pd.pm10.value, 'µg/m³'),
                                    _PollChip('NO₂',   pd.no2.value,  'µg/m³'),
                                    _PollChip('SO₂',   pd.so2.value,  'µg/m³'),
                                    _PollChip('O₃',    pd.o3.value,   'µg/m³'),
                                    _PollChip('CO',    pd.co.value,   'µg/m³'),
                                  ]),
                          ),
                          const SizedBox(height: 14),

                          // ── ML Prediction ──────────────────────
                          _ReportSection(
                            title: 'ML Prediction (1-Hour Ahead)',
                            icon : Icons.psychology_rounded,
                            iconColor: const Color(0xFF6C63FF),
                            child: ml == null
                                ? const Text('ML prediction not available.',
                                    style: TextStyle(fontSize: 12,
                                        color: AppTheme.textSecondary))
                                : Column(children: [
                                    _ReportRow('Predicted AQI',
                                        ml.predictedAqi.toStringAsFixed(1)),
                                    _ReportRow('Trend',
                                        '${ml.trend}  (${ml.change})'),
                                    _ReportRow('Confidence', ml.confidencePct),
                                    _ReportRow('MAE',
                                        '±${ml.mae.toStringAsFixed(1)} AQI'),
                                    _ReportRow('Source',
                                        ml.isOnline ? 'Python ML API' : 'Rule-based'),
                                  ]),
                          ),
                          const SizedBox(height: 14),

                          // ── 7-day summary ──────────────────────
                          _ReportSection(
                            title: '7-Day Summary',
                            icon : Icons.calendar_month_rounded,
                            iconColor: const Color(0xFFFF9800),
                            child: week.isEmpty
                                ? const Text('No readings in the last 7 days. '
                                    'Use Analyze to save readings.',
                                    style: TextStyle(fontSize: 12,
                                        color: AppTheme.textSecondary))
                                : Wrap(spacing: 8, runSpacing: 8, children: [
                                    _StatBadge('Readings', '${week.length}',
                                        AppTheme.primaryBlue),
                                    _StatBadge('Avg AQI',
                                        avg.toStringAsFixed(1),
                                        const Color(0xFF9C27B0)),
                                    _StatBadge('Best',
                                        aqis.reduce((a,b)=>a<b?a:b)
                                            .toStringAsFixed(1),
                                        AppTheme.safeGreen),
                                    _StatBadge('Worst',
                                        aqis.reduce((a,b)=>a>b?a:b)
                                            .toStringAsFixed(1),
                                        AppTheme.hazardousRed),
                                    _StatBadge('Safe Days',
                                        '${aqis.where((a)=>a<=50).length}',
                                        AppTheme.safeGreen),
                                  ]),
                          ),
                          const SizedBox(height: 14),

                          // ── Health recs ────────────────────────
                          _ReportSection(
                            title: 'Health Recommendations',
                            icon : Icons.favorite_rounded,
                            iconColor: const Color(0xFFE91E63),
                            child: Column(
                              children: _healthRecs(aqi.latestStatus)
                                  .map((r) => Padding(
                                    padding: const EdgeInsets.only(bottom: 6),
                                    child: Row(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                      const Text('• ',
                                          style: TextStyle(
                                              color: AppTheme.primaryBlue,
                                              fontWeight: FontWeight.w800)),
                                      Expanded(child: Text(r,
                                          style: const TextStyle(
                                              fontSize: 12,
                                              color: AppTheme.textPrimary,
                                              height: 1.4))),
                                    ]),
                                  ))
                                  .toList(),
                            ),
                          ),
                          const SizedBox(height: 20),

                          // ── Share button ───────────────────────
                          SizedBox(
                            width: double.infinity,
                            child: ElevatedButton.icon(
                              onPressed: _generating ? null : _shareReport,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: AppTheme.primaryBlue,
                                foregroundColor: Colors.white,
                                disabledBackgroundColor:
                                    AppTheme.primaryBlue.withOpacity(0.50),
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(14)),
                                padding: const EdgeInsets.symmetric(
                                    vertical: 16),
                              ),
                              icon: _generating
                                  ? const SizedBox(width: 18, height: 18,
                                      child: CircularProgressIndicator(
                                          strokeWidth: 2,
                                          color: Colors.white))
                                  : const Icon(Icons.share_rounded, size: 20),
                              label: Text(
                                _generating
                                    ? 'Generating report…'
                                    : 'Share / Download Report',
                                style: const TextStyle(
                                    fontSize: 15, fontWeight: FontWeight.w700),
                              ),
                            ),
                          ),
                          const SizedBox(height: 10),

                          // ── Format note ────────────────────────
                          const Center(
                            child: Text(
                              'Report is shared as formatted text — '
                              'paste into Notes, WhatsApp, or email.',
                              textAlign: TextAlign.center,
                              style: TextStyle(fontSize: 10,
                                  color: AppTheme.textLight),
                            ),
                          ),
                          const SizedBox(height: 24),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}

// ─────────────────────────────────────────────────────────────
// Helper widgets
// ─────────────────────────────────────────────────────────────
class _ReportSection extends StatelessWidget {
  final String   title;
  final IconData icon;
  final Color    iconColor;
  final Widget   child;
  const _ReportSection({
    required this.title, required this.icon,
    required this.iconColor, required this.child,
  });

  @override
  Widget build(BuildContext context) => Container(
    width: double.infinity,
    decoration: BoxDecoration(
      color: AppTheme.cardBg,
      borderRadius: BorderRadius.circular(16),
      boxShadow: AppTheme.cardShadow,
    ),
    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Padding(
        padding: const EdgeInsets.fromLTRB(14, 12, 14, 8),
        child: Row(children: [
          Icon(icon, size: 16, color: iconColor),
          const SizedBox(width: 8),
          Text(title, style: const TextStyle(fontSize: 13,
              fontWeight: FontWeight.w800, color: AppTheme.textPrimary)),
        ]),
      ),
      const Divider(height: 1, indent: 14, endIndent: 14),
      Padding(padding: const EdgeInsets.all(14), child: child),
    ]),
  );
}

class _ReportRow extends StatelessWidget {
  final String label, value;
  const _ReportRow(this.label, this.value);
  @override
  Widget build(BuildContext context) => Padding(
    padding: const EdgeInsets.only(bottom: 4),
    child: Row(children: [
      Text('$label: ', style: const TextStyle(fontSize: 11,
          color: AppTheme.textSecondary)),
      Text(value, style: const TextStyle(fontSize: 11,
          fontWeight: FontWeight.w700, color: AppTheme.textPrimary)),
    ]),
  );
}

class _PollChip extends StatelessWidget {
  final String  name;
  final double? value;
  final String  unit;
  const _PollChip(this.name, this.value, this.unit);
  @override
  Widget build(BuildContext context) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
    decoration: BoxDecoration(
      color: AppTheme.scaffoldBg,
      borderRadius: BorderRadius.circular(8),
      border: Border.all(color: AppTheme.textLight.withOpacity(0.50)),
    ),
    child: Column(children: [
      Text(name, style: const TextStyle(fontSize: 9,
          color: AppTheme.textSecondary)),
      Text(value != null ? '${value!.toStringAsFixed(1)} $unit' : '—',
          style: const TextStyle(fontSize: 11,
              fontWeight: FontWeight.w700, color: AppTheme.textPrimary)),
    ]),
  );
}

class _StatBadge extends StatelessWidget {
  final String label, value;
  final Color  color;
  const _StatBadge(this.label, this.value, this.color);
  @override
  Widget build(BuildContext context) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
    decoration: BoxDecoration(
      color: color.withOpacity(0.08),
      borderRadius: BorderRadius.circular(10),
      border: Border.all(color: color.withOpacity(0.25)),
    ),
    child: Column(children: [
      Text(label, style: const TextStyle(
          fontSize: 9, color: AppTheme.textSecondary)),
      Text(value, style: TextStyle(fontSize: 14,
          fontWeight: FontWeight.w800, color: color)),
    ]),
  );
}
